/**SUBMISSION CONSTANTS */
export const GET_ALL_SUBMISSIONS = "GET_ALL_SUBMISSIONS";
export const ADD_SUBMISSION = "ADD_SUBMISSION";
export const REMOVE_SUBMISSION = "REMOVE_SUBMISSION";
export const UPDATE_SUBMISSION = "UPDATE_SUBMISSION";

/**WORKSHOPS CONSTANTS */
export const GET_ALL_WORKSHOPS = "GET_ALL_WORKSHOPS";
export const ADD_WORKSHOP = "ADD_WORKSHOP";
export const UPDATE_WORKSHOP = "UPDATE_WORKSHOP";
export const UPDATE_WORKSHOPBY_ID = "UPDATE_WORKSHOPBY_ID";
export const DELETE_WORKSHOP = "DELETE_WORKSHOP";

/**CONFERENCE CONSTANTS */
export const ADD_CONFERENCE = "ADD_CONFERENCE";
export const GET_ALL_CONFERENCE = "GET_ALL_CONFERENCE";
export const EDIT_CONFERENCE = "EDIT_CONFERENCE";
export const DELETE_CONFERENCE = "DELETE_CONFERENCE";

/**DOCUMENT CONSTANTS */
export const ADD_DOCUMENTS = "ADD_DOCUMENTS";
export const RESEARCH = "RESEARCH";
export const W_PROPOSAL = "W_PROPOSAL";
export const PENDING = "PENDING"
export const SET_IN_PROGRESS = "SET_IN_PROGRESS"

export const ADMIN = "ADMIN"
export const TEMPLATE = "TEMPLATE"
